name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:

  push:
    branches:
      - dev
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "**.md"
      - "assets/**"

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt install \
              pandoc \
              texlive-latex-base \
              texlive-fonts-recommended \
              texlive-extra-utils \
              texlive-latex-extra \
              texlive-xetex

      - name: Convert to PDF
        run: |
          mkdir pdfs
          pandoc --pdf-engine=xelatex homework1.md -o pdfs/homework1.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
